<?php
declare(strict_types=1);

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BloodPressureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloodPressureRepository extends EntityRepository {
    use ArrayExceptionCommon;
    /**
     * @param string $patientId
     *
     * @return array
     */
    public function getLast10BloodPressuresForPatientId(string $patientId): array {
        $query = $this->createQueryBuilder('b')
                      ->select('b')
                      ->where('b.patient = :id')
                      ->setParameter('id', $patientId)
                      ->setMaxResults(10)
                      ->getQuery();
        try {
            $bps = $query->getResult();
        } catch (\Throwable $e) {
            return $this->exceptionAsArray($e);
        }
        return $bps;
    }
}
