<?php
declare(strict_types=1);

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * BloodPressureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloodPressureRepository extends EntityRepository {
    /**
     * @param string $patientId
     *
     * @return array
     */
    public function getLast10BloodPressuresForPatientId(string $patientId): array {
        $query = $this->createQueryBuilder('b')
                      ->where('b.patient = :id')
                      ->join('b.locationUsed', 'l')
                      ->join('b.createdBy', 'u')
                      ->setParameter('id', $patientId)
                      ->setMaxResults(10)
                      ->getQuery();
        try {
            $bps = $query->getArrayResult();
            foreach ($bps as &$bp) {
                unset($bp['patient']);
            }
        } catch (\Throwable $e) {
            var_dump($e->getMessage());
            return [];
        }
        return $bps;
    }
}
