<?php

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BloodPressureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloodPressureRepository extends EntityRepository {
    public function getLast10BloodPressuresForPatientId(string $patientId) {
        try {
            $qb = $this->createQueryBuilder('b');
            $bps =
                $qb->where('b.patient = :id')
                   ->join('b.locationUsed', 'l')
                   ->join('b.createdBy', 'u')
                   ->setParameter('id', $patientId)
                   ->setMaxResults(10)
                   ->getQuery()
                   ->getArrayResult();
            foreach ($bps as &$bp) {
                unset($bp['patient']);
            }
        } catch (\Throwable $e) {
            var_dump($e->getMessage());
            return [];
        }
        return $bps;
    }
}
