<?php

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MethodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MethodRepository extends EntityRepository {
}
