<?php
declare(strict_types=1);
/**
 * Contains class PermissionRepository.
 *
 * PHP version 7.2+
 *
 * LICENSE:
 * This file is part of ChartItMD.
 * Copyright (C) 2019 ChartItMD Development Group
 *
 * Additional code from {@link https://github.com/potievdev/slim-rbac} with MIT
 * license by Abdulmalik Abdulpotiev.
 *
 * @see       MIT_LICENSE
 * @author    Abdulmalik Abdulpotiev <potievdev@gmail.com>
 *
 * @author    Michael Cummings <mgcummings@yahoo.com>
 * @copyright 2019 ChartItMD Development Group
 * @license   Proprietary
 */

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PermissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PermissionRepository extends EntityRepository {
    /**
     * Finds permission by name. If it founded returns permission id
     *
     * @param string $name
     *
     * @return string|null
     * @throws \InvalidArgumentException
     * @throws \RuntimeException
     */
    public function getPermissionIdByName(string $name): ?string {
        $qb = $this->createQueryBuilder('permission');
        $result = $qb->select('permission.id')
                     ->where(
                   $qb->expr()
                      ->eq(
                          'permission.name',
                          $qb->expr()
                             ->literal($name)
                      )
               )
                     ->setMaxResults(1)
                     ->getQuery()
                     ->getArrayResult();
        return 0 < count($result) ? $result[0]['id'] : null;
    }
}
