<?php
declare(strict_types=1);
/**
 * Contains class RoleRepository.
 *
 * PHP version 7.2+
 *
 * LICENSE:
 * This file is part of ChartItMD.
 * Copyright (C) 2019 ChartItMD Development Group
 *
 * Additional code from {@link https://github.com/potievdev/slim-rbac} with MIT
 * license by Abdulmalik Abdulpotiev.
 *
 * @see       MIT_LICENSE
 * @author    Abdulmalik Abdulpotiev <potievdev@gmail.com>
 *
 * @author    Michael Cummings <mgcummings@yahoo.com>
 * @copyright 2019 ChartItMD Development Group
 * @license   Proprietary
 */

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoleRepository extends EntityRepository {
    /**
     * @param string $name
     *
     * @return string|null
     * @throws \InvalidArgumentException
     * @throws \RuntimeException
     */
    public function getRoleIdByName(string $name): ?string {
        $qb = $this->createQueryBuilder('role');
        $result =
            $qb->select('role.id')
               ->where(
                   $qb->expr()
                      ->eq(
                          'role.name',
                          $qb->expr()
                             ->literal($name)
                      )
               )
               ->setMaxResults(1)
               ->getQuery()
               ->getArrayResult();
        return 0 < count($result) ? $result[0]['id'] : null;
    }
}
