<?php

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UnitOfMeasurementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitOfMeasurementRepository extends EntityRepository {
}
