<?php
declare(strict_types=1);
/**
 * Contains class UserRoleRepository.
 *
 * PHP version 7.2+
 *
 * LICENSE:
 * This file is part of ChartItMD.
 * Copyright (C) 2019 ChartItMD Development Group
 *
 * Additional code from {@link https://github.com/potievdev/slim-rbac} with MIT
 * license by Abdulmalik Abdulpotiev.
 *
 * @see       MIT_LICENSE
 * @author    Abdulmalik Abdulpotiev <potievdev@gmail.com>
 *
 * @author    Michael Cummings <mgcummings@yahoo.com>
 * @copyright 2019 ChartItMD Development Group
 * @license   Proprietary
 */

namespace ChartItMD\Model\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\QueryException;

/**
 * UserRoleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRoleRepository extends EntityRepository {
    /**
     * @param string $userId
     *
     * @return array
     * @throws QueryException
     * @throws \InvalidArgumentException
     * @throws \RuntimeException
     */
    public function getUserRoleIds(string $userId): array {
        $qb = $this->createQueryBuilder('userRole');
        $qb->select('userRole.roleId')
           ->where(
               $qb->expr()
                  ->eq('userRole.userId', $userId)
           )
           ->indexBy('userRole', 'userRole.roleId');
        $roleIds =
            $qb->getQuery()
               ->getArrayResult();
        return array_keys($roleIds);
    }
}
